set tests [find $srcdir/$subdir *.sh]

set pwd [pwd]

set env(PATH) $pwd/$srcdir/scripts:$::env(PATH)

foreach test $tests {
    global runtests

    set basename [exec basename $test]

    if ![runtest_file_p $runtests $basename] {
	continue
    }

    set required_execs []
    if { $basename == "pr24171.sh" } {
	lappend required_execs "dw2-restrict"
    }

    set unsupported 0
    foreach required_exec $required_execs {
	set size [file size $required_exec]
	if { $size == 0 } {
	    set unsupported 1
	}
    }
    if { $unsupported == 1 } {
	unsupported "$test"
	continue
    }

    set dir $pwd/tmp.$basename
    exec rm -Rf $dir
    exec mkdir $dir

    cd $dir
    if { [catch { exec sh -e ../$test } msg] } {
	puts "$msg"
	fail "$test"
    } else {
	set file_list [glob -nocomplain "$dir/*"]
	if {[llength $file_list] != 0} {
	    puts "$dir is not empty"
	    fail "$test"
	} else {
	    pass "$test"
	    exec rm -Rf $dir
	}
    }
    cd $pwd
}
